# Generated by Django 5.1.3 on 2024-11-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=5899),
        ),
    ]
