# Generated by Django 5.1.3 on 2024-11-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_register_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='number',
            field=models.IntegerField(default=1234567890),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=2978),
        ),
    ]
