# Generated by Django 5.1.3 on 2024-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_register_address_register_city_register_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=5167),
        ),
    ]
