# Generated by Django 5.1.3 on 2024-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_register_address_alter_register_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.IntegerField()),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=9648),
        ),
    ]
