# Generated by Django 5.1.3 on 2024-11-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_category_alter_register_token_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=4420),
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
