# Generated by Django 5.1.3 on 2024-11-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=2458),
        ),
        migrations.AddField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.subcategory'),
        ),
    ]
