# Generated by Django 5.1.3 on 2024-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_subcategory_alter_register_token_product_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=9351),
        ),
    ]
