# Generated by Django 5.1.3 on 2024-11-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_register_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quilty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcat',
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=7725),
        ),
    ]
