# Generated by Django 5.1.3 on 2024-11-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_product_quality_alter_register_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=6628),
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
