# Generated by Django 5.1.3 on 2024-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_register_token_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='register',
            name='token',
            field=models.IntegerField(default=2529),
        ),
    ]
